services:
  share-and-tell:
    build: .
    container_name: share-and-tell
    volumes:
      - ./sample-share:/share:ro
      - ./reports:/output
  command: ["--format", "all", "--output", "/output", "/share"]
