name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run test suite
        run: pytest
